@startuml
class BrickBreakerGame {
  -WIDTH: int
  -HEIGHT: int
  -ball: Ball
  -paddle: Paddle
  -bricks: List<Brick>
  -buffer: BufferedImage
  -bufferGraphics: Graphics

  +Server()
  +update(bufferGraphics: Graphics): void
  +paint(g: Graphics): void
}

class Ball {
  -SIZE: int
  -x: int
  -y: int
  -angle: double
  -speed: double

  +Ball(x: int, y: int)
  +move(): void
  +reverseX(): void
  +reverseY(): void
  +setAngle(newAngle: double): void
  +getX(): int
  +getY(): int
  +getBounds(): Rectangle
  +draw(g: Graphics): void
}

class Paddle {
  -WIDTH: int
  -HEIGHT: int
  -x: int
  -y: int

  +Paddle(x: int, y: int)
  +move(mouseX: int): void
  +getX(): int
  +getY(): int
  +getBounds(): Rectangle
  +draw(g: Graphics): void
}

class Brick {
  -SIZE: int
  -x: int
  -y: int

  +Brick(x: int, y: int)
  +getX(): int
  +getY(): int
  +getBounds(): Rectangle
  +draw(g: Graphics): void
}

class Client {
  -buffer: BufferedImage
  -bufferGraphics: Graphics

  +main(args: String[]): void
  +Server(): void
  +paint(g: Graphics): void
}

BrickBreakerGame --> Ball
BrickBreakerGame --> Paddle
BrickBreakerGame --> Brick
Client --> Ball
Client --> Paddle
Client --> Brick
@enduml
