@startuml

actor client
participant myFrame
participant myPanel
participant Server
participant Ball
participant Paddle
participant Brick
participant PowerUp

client -> Server: Start
myFrame -> myPanel: Start
myPanel -> myFrame: setData(data)
client -> myFrame: Move Paddle
myFrame -> myPanel: repaint()
myPanel -> myFrame: paint(g)
myFrame -> myPanel: drawPaddle(g, x, y, width, height, id)
myFrame -> myPanel: drawBall(g, x, y, size, owner)
myFrame -> myPanel: drawBricks(g, x, y, width, height, hp)
myPanel -> Server: update(inputLine)
Server -> Server: handleClient(clientSocket, id)
Server -> Server: checkCollision()
Server -> Ball: Check Collision
Ball -> Paddle: Check Collision
Paddle -> Server: Hit Paddle
Server -> Brick: Check Collision
Brick -> Server: Hit Brick
Server -> PowerUp: Check Collision
PowerUp -> Server: RollaPowerup()
PowerUp -> PowerUp: fall()
Server -> client: update(outputLine)
myFrame -> myPanel: gameOver(g, id1, score1, id2, score2)
myFrame -> myPanel: repaint()
myPanel -> myFrame: paint(g)
myFrame -> myPanel: gameOver(g, id1, score1, id2, score2)
myFrame -> myPanel: repaint()
myPanel -> client: immagine

@enduml
