@startuml

left to right direction

actor Client as "Client"
actor Server as "Server"
boundary Game as "Myframe"
boundary info as "Info"

Client --> (Start Game)
Client --> (Move Paddle)

(Start Game) --> Server: Start Game
(Move Paddle) --> Server: Move Paddle
(Move Paddle) --> (Hit Brick)
(Move Paddle) --> (Missed Ball)
(Move Paddle) --> (End Game)
(Hit Brick) --> Server: Move Paddle
(Missed Ball) --> Server: Move Paddle
(End Game) --> Server: Move Paddle

(Server) --> (Game): Print info
(Game) --> info: Image
(Server) --> (info): Update Game State
info --> Client

@enduml
