left to right direction

actor Client as "Client"
actor Server as "Server"
boundary Game as "Game"

Client --> (Start Game)
Client --> (Move Paddle)
Client --> (Hit Brick)
Client --> (Missed Ball)
Client --> (End Game)

(Start Game) --> Server: Start Game
(Move Paddle) --> Server: Move Paddle
(Hit Brick) --> Server: Hit Brick
(Missed Ball) --> Server: Missed Ball
(End Game) --> Server: End Game

(Server) --> (Game): Informazioni da stampare
(Game) --> (Client): Immagine da stampare
(Server) --> (Client): Update Game State

@enduml