@startuml
left to right direction

actor Client as "Client"
actor Server as "Server"

Client --> (Start Game)

Client --> (Move Paddle)

(Start Game) --> Server
(Move Paddle) --> Server
(Hit Brick) --> Server
(Missed Ball) --> Server
(End Game) --> Server

(Start Game) --> (Move Paddle)
(Start Game) --> (Hit Brick)
(Move Paddle) --> (Hit Brick)
(Hit Brick) --> (Missed Ball)
(Missed Ball) --> (End Game)
(Server) --> (Client): Informazioni da stampare

@enduml